name: CI
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build binaries
        run: go build ./...
